### ISSUE TITLE
las compras por TPV deberían mostrar importes negativos en la tabla de movimientos de sociasmercao

### ISSUE THREAD

**Issue by gentooza** [kaostc/tpvmercao#1]
cuando se compra por TPV, el importe debería salir negativo en el resumen de una socia, adjunto captura:
![Captura desde 2023-05-25 10-25-31](https://github.com/kaostc/tpvmercao/assets/10772286/ad7853fa-e21d-4f87-beb0-a23c36ba8c7d)

**Comment by kaostc** [comment]
Corregido.
![imagen](https://github.com/kaostc/tpvmercao/assets/131990611/da441013-0055-4f70-87a9-ec26b80533c8)
